### ISSUE TITLE
SSH

### ISSUE THREAD

**Issue by JDillon522** [rumaner/training#6]
If CodeSchool didnt cover it yet, you're probably having to enter in your github username and password every time you push to your repo. Thats because your remotes are using HTTPS and not SSH.

Regardless, sending things over SSH is more secure and necessary in any sort of production work. 

Go through githubs help pages and learn what using SSH entails and then set it up on your account.

**Comment by rumaner** [comment]
hey i used Youtube and figured it out(better than github's own help websites) so I'm gonna close this now.
