### ISSUE TITLE
Add Scss

### ISSUE THREAD

**Issue by JDillon522** [rumaner/training#7]
Add SASS to your project. 

This might, or might not, be a huge pain in the ass.

Reference the [SASS Documentation](http://sass-lang.com/) on how to get started. 

When you get it installed take a look at [this part of the documentation](http://sass-lang.com/documentation/file.SASS_REFERENCE.html#using_sass) on how to actually use SASS on your machine.

Add a `main.scss` file in your `styles` directory and have it properly compile into `main.css`

**Comment by rumaner** [comment]
i learned how to have my terminal monitor changes in my main.scss file and make those changes to my main.css by typing in sass --watch main.scss:main.css

**Comment by rumaner** [comment]
do you want me to actually add sass to the project or is this issue closed?

**Comment by JDillon522** [comment]
Create a branch named after the ticket and make a PR that demonstrates that it works. 

Good job btw

**Comment by JDillon522** [comment]
fixed by #19
